[package]
name = "btletoy"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.5"
env_logger = "0.11.5"
futures = "0.3.30"
log = "0.4.22"
rand = "0.8.5"
tokio = { version = "1.39.2", features = ["full"] }
uuid = "1.10.0"
common = { path = "../common" }
binary_serde = "1.0.24"
